### ISSUE TITLE
Any way to donate?

### ISSUE THREAD

**Issue by bomberstudios** [runemadsen/programmingdesignsystems.com#1]
I just read the first two chapters and I'm ready to throw money your way if that helps you keep doing this for a living.

Any way of donating to you / the project?

Thanks for an amazing work.

**Comment by runemadsen** [comment]
Thanks so much @bomberstudios. That's very kind of you. Fortunately, I'm being supported by NYU as a research fellow, so the absolute best way to help the project is to share it with the world. Having a big audience really helps :) Thx!
