### ISSUE TITLE
Figure and ground  - typo

### ISSUE THREAD

**Issue by adamprocter** [runemadsen/programmingdesignsystems.com#8]
Line 85 - should say size, margin not margin, margin I believe

**Comment by runemadsen** [comment]
Thanks! I can't find the place you are mentioning. Can you let me know which line in this document?

https://github.com/runemadsen/programmingdesignsystems.com/blob/master/content/shape/figure-and-ground.html

**Comment by adamprocter** [comment]
Line 85 I believe

**Comment by bomberstudios** [comment]
Made a PR, hope it helps!

**Comment by runemadsen** [comment]
Thanks for the PR! The code is actually correct in the current version. The `margin` is simply used to calculate the `x` and `y` position of the rectangle. The `size` is the same for the width and height.

**Comment by bomberstudios** [comment]
Np, hope my next PR actually fixes something! 😅

**Comment by runemadsen** [comment]
:)
